app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('app2/',app2,name='app2'),
]

project22/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',app1,name='app1'),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def app1(request):
    return render(request,'app1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def app2(request):
    return render(request,'app2.html')

templates/app1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is app1 page</h1>
        <h2><a href="{% url 'app2:app2' %}">go to app2</a></h2>
    </center>
</body>
</html>

templates/app2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is app2 page</h1>
        <h2><a href="{% url 'app1' %}">go to app1</a></h2>
    </center>
</body>
</html>